chore: add my project
quic-go/quic-go pull request #4085
Opened 2023-09-15 21:39 UTC by tobyxdd

2023-09-15 21:42 UTC, tobyxdd commented
btw @marten-seemann sorry for not providing updates on the frame sorter optimization PR, I was busy working on the v2 update of this. Will come back to it next week.

2023-09-16 12:17 UTC, marten-seemann approved these changes

2023-09-16 15:46 UTC, marten-seemann requested changes
The list is supposed to be sorted alphabetically by project name. Can you please adjust where you insert Hysteria?

2023-09-22 11:59 UTC, marten-seemann approved these changes

2023-09-24 11:01 UTC, merged