enable DPLPMTUD on macOS dual-stack sockets
quic-go/quic-go pull request #4723
Opened 2024-11-15 10:53 UTC by marten-seemann

My new draft in the TSV WG (https://datatracker.ietf.org/doc/draft-seemann-tsvwg-udp-fragmentation/) contains details on how IP fragmentation is handled on different platforms.

2024-11-26 12:02 UTC, sukunrt approved these changes
This doesn't work for macOS Ventura(13.1). Here the DF bit won't be set and DPLPMTUD will set the max value of 1430. It's 1430 because this is 20 bytes less than the max MTU for ethernet frames. https://github.com/quic-go/quic-go/blob/macos-dplpmtud/mtu_discoverer.go#L25

2024-11-28 10:12 UTC, marten-seemann commented
I updated the PR to test if a socket is a dual-stack socket on older (before Sequoia) macOS versions. If it's a dual-stack socket, DPLPMTUD will be disabled.

2024-11-30 10:38 UTC, sukunrt requested changes

2024-12-01 05:25 UTC, marten-seemann commented on sys_conn_df_darwin.go
> +			if version < 15 {
Fixed by introducing a constant `macOSVersion15`.

2024-12-01 05:25 UTC, marten-seemann commented on sys_conn_df_darwin.go
> +	if err != nil || version < 11 {
Fixed by introducing a constant `macOSVersion11`.

2024-12-01 06:02 UTC, sukunrt approved these changes

2024-12-01 06:50 UTC, merged